# Generated by Django 4.1.1 on 2023-01-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(default='Hello', max_length=10000),
        ),
    ]
