# Generated by Django 4.1.1 on 2023-01-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(max_length=10000),
        ),
    ]
