# Generated by Django 4.1.1 on 2023-01-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_image',
            field=models.ImageField(default='u.jpg', upload_to='project/images'),
        ),
    ]
