# Generated by Django 4.1.1 on 2023-01-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_image',
            field=models.ImageField(upload_to='project/images'),
        ),
    ]
