# Generated by Django 4.1.1 on 2023-01-06 20:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
