# Generated by Django 4.1.1 on 2023-01-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_video',
            field=models.FileField(blank=True, null=True, upload_to='project/videos'),
        ),
    ]
